/**
 * CV content — types and typed accessors.
 *
 * The actual content lives in `cv.json`, which is REGENERATED by
 * `npm run import-cv <file>`. Do not hand-edit that file unless you mean to:
 * the next import overwrites it. Edit this file only to change the shape of
 * the data or add a new section.
 *
 * Every user-visible string is a `Localized` pair so the UI can switch between
 * English and Greek without duplicating any markup.
 */

import data from "./cv.json";

export type Lang = "en" | "el";

/** A string that exists in both supported languages. */
export type Localized = { en: string; el: string };

export interface ContactLink {
  id: string;
  label: Localized;
  value: string;
  /** Ready-to-use href (mailto:, tel: or https:). */
  href: string;
}

export interface EducationEntry {
  degree: Localized;
  institution: Localized;
  period: Localized;
  highlights: Localized[];
}

export interface ExperienceEntry {
  role: Localized;
  organization: Localized;
  location: Localized;
  period: Localized;
  bullets: Localized[];
}

export interface ProjectEntry {
  title: Localized;
  period: Localized;
  items: { name: Localized; description: Localized }[];
}

export interface SkillGroup {
  label: Localized;
  items: string[];
}

export interface LabelledValue {
  label: Localized;
  value: Localized;
}

export interface Certification {
  name: Localized;
  issuer: Localized;
}

export interface Activity {
  title: Localized;
  description: Localized;
}

export interface Person {
  firstName: Localized;
  lastName: Localized;
  headline: Localized;
}

/** Provenance of the current content — shown in the About window. */
export interface CvMeta {
  /** ISO timestamp of the last `npm run import-cv` run, or null if hand-written. */
  generatedAt: string | null;
  /** Original filename the content was extracted from, or "manual". */
  source: string;
  /** Language the source document was written in. */
  sourceLanguage?: Lang;
  /**
   * Languages the site can actually offer.
   *
   * Set by the import from how many documents were supplied. One document in
   * means one language out, and the language switcher disappears rather than
   * offering a translation the author never wrote.
   */
  availableLanguages?: Lang[];
}

export const META = data.meta as CvMeta;
export const PERSON = data.person as Person;
export const CONTACT = data.contact as ContactLink[];
export const PERSONAL_INFO = data.personalInfo as LabelledValue[];
export const SUMMARY = data.summary as Localized;
export const EDUCATION = data.education as EducationEntry[];
export const SKILLS = data.skills as SkillGroup[];
export const CERTIFICATIONS = data.certifications as Certification[];
export const EXPERIENCE = data.experience as ExperienceEntry[];
export const PROJECTS = data.projects as ProjectEntry[];
export const ACTIVITIES = data.activities as Activity[];
